from __future__ import annotations

import uuid
from pydantic import BaseModel, Field, field_validator


class ComparisonRequest(BaseModel):
    """Payload to request a comparative analysis."""

    document_ids: list[uuid.UUID] = Field(
        ...,
        min_items=2,
        max_items=5,
        description="Danh sách ID tài liệu BCTC muốn so sánh (tối thiểu 2, tối đa 5)",
    )

    @field_validator("document_ids")
    @classmethod
    def validate_ids_count(cls, v: list[uuid.UUID]) -> list[uuid.UUID]:
        if len(v) < 2:
            raise ValueError("Phải chọn tối thiểu 2 tài liệu để so sánh.")
        if len(v) > 5:
            raise ValueError("Chỉ hỗ trợ so sánh tối đa 5 tài liệu cùng lúc.")
        return v


class CompanyMeta(BaseModel):
    """Metadata representing an analyzed statement version."""

    document_id: uuid.UUID
    company_name: str
    year: int | None = None
    document_type: str


class AIComparisonEvaluation(BaseModel):
    """Structured textual assessment generated by the AI CFO comparison engine."""

    profitability_comparison: str = Field(
        ...,
        description="Phân tích đối chiếu hiệu suất sinh lời (ROE, ROA, Net Margin) giữa các doanh nghiệp",
    )
    leverage_comparison: str = Field(
        ...,
        description="Phân tích đối chiếu rủi ro đòn bẩy tài chính (Debt Ratio, Debt-to-Equity)",
    )
    liquidity_comparison: str = Field(
        ...,
        description="Phân tích đối chiếu năng lực thanh toán nợ ngắn hạn (Current/Quick Ratio)",
    )
    cfo_verdict: str = Field(
        ...,
        description="Nhận định tổng quan của CFO về doanh nghiệp có sức khỏe tài chính tốt hơn và các lưu ý quyết định",
    )


class ComparisonResponse(BaseModel):
    """
    Unified comparative analysis report returned to the frontend.
    """

    compared_entities: list[CompanyMeta]
    
    # Side-by-side comparison matrix.
    # Format: {"roe": {"Vinamilk 2023": 0.195, "TH True Milk 2023": 0.121}}
    comparison_matrix: dict[str, dict[str, float | None]]

    ai_evaluation: AIComparisonEvaluation
