from __future__ import annotations

from enum import Enum
from pydantic import BaseModel, Field


class PriorityEnum(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class InsightItem(BaseModel):
    """Represents a specific metric evaluation (Strength or Weakness)."""

    metric: str = Field(..., description="Tên chỉ số tài chính (ví dụ: Hệ số nợ, ROE)")
    value: str = Field(..., description="Giá trị chỉ số (ví dụ: 75%, 2.1)")
    analysis: str = Field(..., description="Phân tích chi tiết nguyên nhân và tác động")


class InsightRecommendation(BaseModel):
    """Actionable advice generated by the CFO AI."""

    action: str = Field(..., description="Hành động đề xuất ngắn gọn")
    priority: PriorityEnum = Field(..., description="Độ ưu tiên: HIGH | MEDIUM | LOW")
    detail: str = Field(..., description="Giải thích chi tiết phương án thực hiện")


class FinancialInsightReport(BaseModel):
    """
    Unified Pydantic Schema representing the structured JSON report
    returned by Groq Llama 3.3.
    """

    summary: str = Field(
        ...,
        description="Đoạn tóm tắt tổng quan về sức khỏe tài chính doanh nghiệp (markdown format)",
    )
    strengths: list[InsightItem] = Field(
        default=[],
        description="Danh sách các điểm mạnh/ưu thế tài chính phát hiện được",
    )
    weaknesses: list[InsightItem] = Field(
        default=[],
        description="Danh sách các điểm yếu/cảnh báo rủi ro tài chính phát hiện được",
    )
    recommendations: list[InsightRecommendation] = Field(
        default=[],
        description="Các giải pháp và khuyến nghị hành động tối ưu hóa từ chuyên gia CFO",
    )
